sudo: false

language: c

# Caching so the next build will be fast too.
cache:
  directories:
    - ~/.stack
    - ~/.local
    - ~/.stack-work-cache

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  # Configure stack to use the system GHC installation
  - stack config set system-ghc --global true

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-8.0.2

script:
  - stack --no-terminal --install-ghc --skip-ghc-check test